codecov:
  require_ci_to_pass: no
  disable_default_path_fixes: false
fixes:
  - "./microservices/product-composite-service/"
  - "./microservices/product-service/"
  - "./microservices/recommendation-service/"
  - "./microservices/review-service/"
  - "./spring-cloud/eureka-server/"
  - "./spring-cloud/gateway/"