version: 2.1
orbs:
  codecov: codecov/codecov@1.0.2
jobs:
  build:
    docker:
      - image: circleci/openjdk:8-jdk

    working_directory: ~/repo

    environment:
      JVM_OPTS: -Xmx3200m
      TERM: dumb

    steps:
      - checkout

      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "build.gradle" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-

      - run: gradle dependencies

      - save_cache:
          paths:
            - ~/.gradle
          key: v1-dependencies-{{ checksum "build.gradle" }}

      # run tests!
      - run: gradle test
      
      - codecov/upload:
          file: microservices/product-composite-service/build/reports/jacoco/test/jacocoTestReport.xml
      - codecov/upload:
          file: microservices/product-service/build/reports/jacoco/test/jacocoTestReport.xml
      - codecov/upload:
          file: microservices/recommendation-service/build/reports/jacoco/test/jacocoTestReport.xml
      - codecov/upload:
          file: microservices/review-service/build/reports/jacoco/test/jacocoTestReport.xml